### ISSUE TITLE
RuntimeError: Binary 'sox' could not be found

### ISSUE THREAD

**Issue by muzaif** [Shivam623/Shyna623#1]
Hi, I cloned your project, but for some reason I am getting this error `C:\Python\python.exe C:/Users/HP/Downloads/Shyna623-f70490ab24280d737aee4aa7e2a7c0ed55059b25/Shyna623-f70490ab24280d737aee4aa7e2a7c0ed55059b25/Shyna_speech/Shyna_speak.py
Traceback (most recent call last):
  File "C:/Users/HP/Downloads/Shyna623-f70490ab24280d737aee4aa7e2a7c0ed55059b25/Shyna623-f70490ab24280d737aee4aa7e2a7c0ed55059b25/Shyna_speech/Shyna_speak.py", line 1, in <module>
    from google_speech import Speech
  File "C:\Python\lib\site-packages\google_speech\__init__.py", line 301, in <module>
    bin_dep.check_bin_dependency(("sox",))
  File "C:\Python\lib\site-packages\google_speech\bin_dep.py", line 7, in check_bin_dependency
    raise RuntimeError("Binary '%s' could not be found" % (bin))
RuntimeError: Binary 'sox' could not be found
` 

since I'm new to Python and haven't had much experience with Voice, I am hoping that you would help me!

**Comment by Shivam623** [comment]
Hi,

Sorry for delay, 
It is also mentioned at the google_speech package home page we have to install SoX. 
All you have to do is sudo apt-get install sox libsox-fmt-mp3 at terminal. 

If you are using Windows then please refer the link https://pypi.org/project/google-speech/

I came across the same issue as I forget to install it. 

Thanks.
